### ISSUE TITLE
No support for Security Group definition updates

### ISSUE THREAD

**Issue by mtekel** [cloudfoundry/capi-release#9]
## Issue

When you change existing SG definitions in cf manifest or add new security groups and apply changes with BOSH, the changes are not applied even though instances are updated by BOSH. Behaviour looks similar to https://github.com/cloudfoundry/capi-release/issues/4

## Context

I want to update existing SG or add new SG.

## Steps to Reproduce

Update existing SG or add new SG in CF manifest. Bosh deploy, watch BOSH update controller VM.

## Expected result

Changes are applied and new SGs exist when you do `cf security-groups`.

## Current result

Changes are not applied and no new security groups are created.

## Possible Fix

Either apply changes or at least document that even though changes from manifest are applied against environment, your release is ignoring them.

## Versions
BOSH v255.8, CF v233

**Comment by SocalNick** [comment]
@utako maybe we want to nest all seed properties that are only applied on initial install, something like:

```
properties:
  capi:
    idempotent_setting_a: foo.bar.com
    idempotent_setting_b: baz.bar.com
    seeding_applied_on_initial_install_only:
      seed_setting_a: some-default-quota
      seed_setting_b: some-security-group
```

@mtekel: this is an interesting issue as bosh is definitely designed to apply deployment manifest changes in an idempotent manner. These properties for the Cloud Controller are intended to reduce getting started friction by adding a couple sane defaults to the Cloud Controller. Aside from the above proposed change, we'll consider how we improve our getting started experience while also not breaking the idempotent deploys by bosh.
